name: build
on: push
jobs:
  build:
    steps:
      - uses: actions/checkout@v3

      - run: ./mongodb-arm64-from-source.sh

      - uses: actions/upload-artifact@v3
        with:
          name: mongodb
          path: mongo/bin
