name: build
on: push
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3

      - run: echo """deb [arch=arm64] http://ports.ubuntu.com/ubuntu-ports focal main restricted universe multiverse
deb [arch=arm64] http://ports.ubuntu.com/ubuntu-ports focal-updates main restricted universe multiverse
deb [arch=arm64] http://ports.ubuntu.com/ubuntu-ports focal-security main restricted universe multiverse
deb [arch=amd64] http://us.archive.ubuntu.com/ubuntu/ focal main restricted universe multiverse
deb [arch=amd64] http://us.archive.ubuntu.com/ubuntu/ focal-updates main restricted universe multiverse
deb [arch=amd64] http://security.ubuntu.com/ubuntu focal-security main restricted universe multiverse""" > sources.list
      - run: sudo mv sources.list /etc/apt/sources.list
      - run: sudo dpkg --add-architecture arm64
      - run: sudo apt-get update -y
      - run: sudo apt-get install openssl gcc-10-aarch64-linux-gnu g++-10-aarch64-linux-gnu libssl-dev liblzma-dev libcurl4-openssl-dev -y
      - run: sudo apt-get install  libcurl4:arm64 openssl:arm64 libssl-dev:arm64 liblzma-dev:arm64 libcurl4-openssl-dev:arm64 -y
      - run: git clone -b v6.2 --depth 1 https://github.com/mongodb/mongo.git
      - run: cd mongo && python3 -m pip install --user -r etc/pip/compile-requirements.txt
      - run: sed -i "s/env.ConfError(\"Failed to detect a supported target architecture\")/pass/g" mongo/SConstruct
      - run: sed -i "s/env.ConfError(\"Could not detect processor specified in TARGET_ARCH variable\")/pass/g"  mongo/SConstruct
      - run: sed -i "s/env['TARGET_ARCH'] = detected_processor/env['TARGET_ARCH'] = 'aarch64'/g" mongo/SConstruct
      - run: cd mongo && python3 buildscripts/scons.py --ssl=off  CC=/usr/bin/aarch64-linux-gnu-gcc-10 CXX=/usr/bin/aarch64-linux-gnu-g++-10 TARGET_ARCH="aarch64" DESTDIR="bin" CCFLAGS="-march=armv8-a+crc -mtune=cortex-a72" install-servers

      - uses: actions/upload-artifact@v3
        with:
          name: binary
          path: mongo/bin
      - uses: actions/upload-artifact@v3
        with:
          name: build
          path: mongo/build
